name: Update Market Data

on:
  schedule:
    - cron: "*/5 * * * 1-5"   # every 5 minutes, Mon–Fri
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance pandas pytz

      - name: Generate NIFTY data
        run: python runner.py

      - name: Commit and push data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/nifty.json
          git commit -m "Update NIFTY data" || echo "No changes"
          git push
